### ISSUE TITLE
add mouse drag and swipe feature in jcarousel

### ISSUE THREAD

**Issue by mufaddalmw** [jsor/jcarousel#382]
Can we add mouse drag and swipe feature in jcarousel, so that we can use jcarousel using mouse drag rather that click on arrow for prev and next ? 

I want to add feature like this http://code.ovidiu.ch/dragdealer/

**Comment by satyendera** [comment]
I am using jcarousel and unfortunately not able to change HTML structure for Touch carousel so is there any scripting/library option to make it swipe enable.

**Comment by jsor** [comment]
There is a swipe plugin made by @snake-345, check the [Third-Party Plugins section](https://github.com/jsor/jcarousel#third-party-plugins) of the README.
