### ISSUE TITLE
Feature Jcarousel with wrap: circular shows empty element after the last element in the list

### ISSUE THREAD

**Issue by ChiragKC** [jsor/jcarousel#564]
I've created a feature jcarousel with 3 `li` items in `ul` with wrap set to circular and set the visibility to display only one element. I have also defined overflow visible on the clip to display the previous and next element in the list. The problem occurs when the last item is in the clip.

What's supposed to happen is that the first element in the list should be displayed next in jcarousel-overlay-right. Instead there is a blank item.

Actual result:

---

|**1**|**2**|**3**|   ->     |**2**|**3**|____|

Expected Result:

---

|**1**|**2**|**3**|   ->     |**2**|**3**|**1**|

This issue is also observed when scrolling back to top of the list. The last element is supposed to be displayed in jcarousel-overlay-left whereas a blank item is displayed.

Please do let me know if there is a workaround for this issue.

**Comment by 57u** [comment]
This was never fixed then...?
