### ISSUE TITLE
Can I use ScrollIntoView to center active item?

### ISSUE THREAD

**Issue by OpenHaus** [jsor/jcarousel#581]
I am using the latest master of v0.3. Not sure if it is meant to be a feature or if it is just a coincidence but if I use the config directive to center the items 

```
    var jcar = $j('.jcarousel').jcarousel({
        'center': true
    });
```

and I center an item by code 

```
jcar.jcarousel('scrollIntoView', 3, true);
```

the item will be centered if the newly centered item was on the left of the center. It will not work if the newly centered item is one the right hand side of the visual center.

You can have a look at my implementation and the potential bug here: http://www.podcast.de/radio/

Any hints are welcome!

**Comment by evgenyshev** [comment]
@OpenHaus, can your example? The link 503 error :(
Now I want to make sure that when the page loads the active element (div.active) was in the middle.
