### ISSUE TITLE
Pagination plugin doesn't calculate the active page correctly

### ISSUE THREAD

**Issue by ehynds** [jsor/jcarousel#585]
Depending on the number of items and the number visible per page of the carousel, the pagination plugin fires active.jcarouselpagination event on the wrong page. 

STR:
1. Load this test case: http://plnkr.co/edit/ED8nil3oBnl7iBUbdqtg?p=preview 
2. Click the "next" link twice to move to the last page of the carousel
3. Click the "prev" link to move back one page
4. Observe that the first pagination circle is denoted as active, even though you're on page 2.

This bug occurs because the logic to determine the current page uses the targeted list item in the carousel as if you were progressing forwards through the carousel, not backwards. At step 3 which you click prev, the 4th item in the carousel becomes the target, which happens to be on page 1 when the carousel first loads but due to the odd number of items in the carousel, it is not on page 1 when moving backwards.

**Comment by carlosvillademor** [comment]
In the example you posted above on Plunker, you do not have both plugins working together. I am trying to do so but I am having issues. I have set up https://jsfiddle.net/carlosvillademor/sgwLp0tu/10/ I am doing click on the pagination links when using the prev or next links, but trying to set control links in a way that would handle the active/inactive transitions. Is that possible? If you play up with the example on my jsfiddle, you can see that the inactive or active events on the control link don't work properly. Could you shed some light into what is wrong on my setup? Thanks in advance.

**Comment by jsor** [comment]
I've updated the jsfiddle: https://jsfiddle.net/sgwLp0tu/11/
The only difference is, that i configured the prev-control with `target: '-=1'` so it really acts like a prev-control.

**Comment by carlosvillademor** [comment]
I see, the default for that is '+=1' so it was acting as the next instead. Cool! Thanks. I was assuming that I didn't need the target as the method was doing the move, but yes, that was a wrong assumption. Thanks Jan.

**Comment by carlosvillademor** [comment]
I mistakenly deleted the jsfiddle you corrected. Here is a final version working, https://jsfiddle.net/carlosvillademor/p4cLk90t/, in case is of use for anybody.
