### ISSUE TITLE
[Feature Request] Touch friendly scroll

### ISSUE THREAD

**Issue by timint** [jsor/jcarousel#634]
Swipe left/right to slide would be awesome.

**Comment by snake-345** [comment]
I'm write plugin for adds support swipe gestures. You may use it https://github.com/snake-345/jcarouselSwipe

**Comment by jsor** [comment]
Wow, this is awesome. Works great! Good work :+1:

**Comment by jsor** [comment]
I've added it to the readme: https://github.com/jsor/jcarousel/blob/master/README.md#third-party-plugins
