### ISSUE TITLE
jCarousel 0.3.1 not working in Safari PC 5.1.7 (7534.57.2)

### ISSUE THREAD

**Issue by rweiler** [jsor/jcarousel#681]
I am using jCarousel 0.3.1 on a site (http://vsgroup.ca/) and the plugin is not working.  The plugin throws the following error: TypeError: 'null' is not an object (evaluating 'this._visible.index').
It only seems to happen on the PC version of Safari (it works fine in the Mac version, as well as Chrome, FireFox and IE).
I'm hoping that can figure out why it's not working and provide a fix.
Thanks

**Comment by krissbennett** [comment]
Did you find a fix on this? Hitting the same problem.
