### ISSUE TITLE
Pagination not restored on reload()

### ISSUE THREAD

**Issue by cmcnaught** [jsor/jcarousel#708]
Having modified the item list via Ajax/javascript, the pagination still retains the old number of items and doesn't update when list is scrolled after calling reload().
Is there a way to 'reload' the pagination?

**Comment by Vovan2006** [comment]
Hi Jan,
Thanks for Jcarousel !
When you press the button pagination I upload new ellementy carousel and then reload carousel. This becomes the first active ellement. How can I make the active ellement which I pressed?
