### ISSUE TITLE
Multiple Dynamic Carousel on the same page

### ISSUE THREAD

**Issue by vikasdream** [jsor/jcarousel#713]
Hi,

I want to show multiple carousel on the same page and for this I'm generating those carousel dynamically not static. Also I'm calling a .js file with all configuration options.

But main problem is that all the carousel is not working together on the same page means if I click on the next button of one carousel other carousels items is moving which is wrong. 

Each carousel should work separately.  

How do we attach the prev() and next() events to specific carousels, and not every carousel? 

Please let me know it is possible or not with jcarousel. Can you please guide me how can i achieve this functionality. 

Through Jcarousel I achieved a lot but for this issue I'm not getting the right solution please help me.

Thanks a lot.

Viki

**Comment by 6clicks** [comment]
Sorry I don't see how to do that with responsive carousel?  

the carousel is called in jcarousel.responsive.js right? ( no other initialization?) 

What exactly I have to change on it to have 2 different carousel ? 

sorry about that... maby it's me ....

**Comment by jsor** [comment]
[My comment](#issuecomment-62602668) was a reply to the [previous comment](#issuecomment-62521965) which mentions the responsive example. I have explained in the [following comment](#issuecomment-62864985) how to use 2 different carousel.

**Comment by 6clicks** [comment]
Sorry I must be stupid... I can not di it... where exactly I have to put this code. I tried in a separate .js file. 
I tried at the en fo jcarousel.responsive.js. I tried at the bottom of my document. 

I am lost...  I have my tow carousel with my tow classes( .jcarousel1 and .jcarousel2)
my css work fine .. I miss juste de correct config ti have the dynamic width.. 
can you help me la little? sorry about that...

**Comment by jsor** [comment]
If you provde i reproducible test-case on jsfiddle or similar i can try to help.

**Comment by 6clicks** [comment]
Thank's but it's a local dev in wordpress.. 

I Will try to reproduce it but it's not shure I can made it. 

maybe you have an URL with a working demo or live? ... in any case Thank's a lot for the support.

**Comment by 6clicks** [comment]
Have You find my mistake some where? thank's a lot.

**Comment by jsor** [comment]
In your markup you use `.jcarousel1-control-prev` but in your js code you use `.jcarousel1-prev`. Same for the next control.

**Comment by 6clicks** [comment]
Harggg  thank's .... I have still the problem with the responsive with... I have to do some thing but I don't know what? ... thank a lot! you rocks!

**Comment by jsor** [comment]
Just use the same code for both carousels: http://codepen.io/anon/pen/qEXxxY

**Comment by 6clicks** [comment]
YES!!! thank's a lot!!!!!

**Comment by digiTeam** [comment]
Hi,

Can you do this with autoscroll?  I can only get one carousel to fire.  The one that fires is the function that is hit first:, so I know both carousels are working.  I have:

        var lCarousel = $('.jcarousel').jcarousel({
             //Configuration goes here
             wrap: 'circular'
        })
        
        
        var sCarousel = $('.jcarouselSmall').jcarousel({
            // Configuration goes here
            wrap: 'circular',
            vertical: true
        })
        
        .jcarouselAutoscroll({
            interval: 3000,
            target: '+=1',
            autostart: true,
            carousel: lCarousel
        })
        .jcarouselAutoscroll({
           interval: 3000,
           target: '+=1',
           autostart: true,
          carousel: sCarousel
        })

I would really appreciate some guidance.

Thanks,

Amanda
