### ISSUE TITLE
Jcarousel broken on refresh

### ISSUE THREAD

**Issue by webmastersdesign** [jsor/jcarousel#737]
i'm usng Jcarousel on my prestashop ecommerce website and each time i reload the website Jcarousel will display longlist of image down.....
![untitled-1](https://cloud.githubusercontent.com/assets/10741746/5938115/376e1c4a-a6f8-11e4-8a9d-584f0f118245.jpg)

**Comment by jsor** [comment]
Could you please setup a reproducible test case in jsfiddle or similar?

**Comment by webmastersdesign** [comment]
http://tiskies.com/index.php   that is url of shop...take a look at it in there

**Comment by jsor** [comment]
I'm only seeing a maintenance page.

**Comment by webmastersdesign** [comment]
http://tiskies.com/index.php  i have open it now.... thanks

**Comment by jsor** [comment]
I see an error in the console (`ReferenceError: comparedProductsIds is not defined`). You should fix that first to ensure its not blocking anything else.

**Comment by webmastersdesign** [comment]
Ok...

**Comment by webmastersdesign** [comment]
Clear th error now getting 	
TypeError: $ is not a function	
$('#products_slider').jcarousel({

**Comment by webmastersdesign** [comment]
found the issue ...solve the problem.....thanks for your time jsor
