### ISSUE TITLE
Scrolling to last item is position-dependant

### ISSUE THREAD

**Issue by KintarD** [jsor/jcarousel#738]
http://jsfiddle.net/ww8Lkpqs/2/ - there, first two case shows work of "scrollTail" function (first on div with static positioning, second on div with relative positioning), and second - work of "scroll" function. Due to list.position calls in scrollTail function - it works different.

While adding "position: relative" to your jcarousel containers is not a big deal, i still think that this should at least be reflected somewhere in documentation

**Comment by alvarovazquez** [comment]
It is actually reflected, isn't it?


From [jCaousel installation doc](http://sorgalla.com/jcarousel/docs/reference/installation.html#style-the-carousel):

```
/*
This is the visible area of you carousel.
Set a width here to define how much items are visible.
The width can be either fixed in px or flexible in %.
Position must be relative!
*/
.jcarousel {
    position: relative;
    overflow: hidden;
}
[...]
```

**Comment by KintarD** [comment]
oops.. sorry(
