### ISSUE TITLE
After install the jcarrousel, elfinder.js doesn't work 

### ISSUE THREAD

**Issue by hookmad** [jsor/jcarousel#739]
After install the jcarrousel, elfinder.js doesn't work when I need use the popup for the link. I think that the version of jquery is top of 1.10.  I need execute jcarrousel with the jquery version lower that 1.10
thanks for your advance.

**Comment by jsor** [comment]
jCarousel should work with jQuery 1.7 or higher. Could you setup a reproducible test case?
