### ISSUE TITLE
It's not an issue but an information for you

### ISSUE THREAD

**Issue by wocmultimedia** [jsor/jcarousel#743]
Hi,
in your website none of the example works on latest version of Chrome 32 bit all pictures links are broken. 
- One question is possible to achieve similar work with your plugin? http://www.discovernorthernireland.com/

Thanks

Angelo

**Comment by jsor** [comment]
Thanks, the example pages are fixed now.

Regarding the slider example, i fear it is not fully possible at the moment. At least #486 should be implemented.

**Comment by wocmultimedia** [comment]
Hi Jsor,
thank you for the quick support reply. I'm also glad I helped you to fix the website. 
Thanks a lot again. Have a great time
Angelo
