### ISSUE TITLE
hasNext/Prev with center option

### ISSUE THREAD

**Issue by Alessandro133** [jsor/jcarousel#746]
I this there should be something like that in hasNext()
**(this.options('center') && this.index(this._target) < end) ||**

            return end >= 0 && !this.underflow &&
                ((wrap && wrap !== 'first') ||
                    (this.index(this._last) < end) ||
                    (this.options('center') && this.index(this._target) < end) ||
                    (this.tail && !this.inTail)) ? true : false;

and in hasPrev
**(this.options('center') && this.index(this._target) >0) ||**

            return this.items().length > 0 && !this.underflow &&
                ((wrap && wrap !== 'last') ||
                    (this.index(this._first) > 0) ||
                    (this.options('center') && this.index(this._target) >0) ||
                    (this.tail && this.inTail)) ? true : false;

**Comment by jsor** [comment]
Can you elaborate what problem this code solves?

**Comment by Alessandro133** [comment]
In "center mode" visibility doesn't matter on activity on next/prev controls. Only current target matter.
Btw, I've end up with this, because of .underflow :

            if (this.options('center'))
                return this.index(this._target) <end;
            else
                return 
                (end >= 0 && !this.underflow &&
                ((wrap && wrap !== 'first') ||
                    (this.index(this._last) < end) ||
                    (this.tail && !this.inTail))) ? true : false;

**Comment by jsor** [comment]
Got it. Fixed in 31e28db. Thanks!
