### ISSUE TITLE
Circular bug

### ISSUE THREAD

**Issue by Craigy-** [jsor/jcarousel#747]
Hello!
In my circular carousel after two scrolls to the next slide occurs bug when I see previous slide before scroll starts. Same thing when I'm scroll it to prev - but it occurs at once. It visually looks bad... Where I'm wrong?
Demo - http://craigy.ru/t/jcarousel/

**Comment by jsor** [comment]
Try to remove the padding from the root element (`.jcarousel-container`).

**Comment by Craigy-** [comment]
Yes, it has helped, thank you. Although that paddings for me is much more convenient.
