### ISSUE TITLE
Pagination and autoscroll

### ISSUE THREAD

**Issue by teodors** [jsor/jcarousel#749]
From what I can tell, pagination doesn't work with autoscroll. If autoscroll is enabled, then pagination doesn't change currently active item. I am using Pagination and Autoscroll plugins.

**Comment by jsor** [comment]
It should work together. Can you setup a reproducible test case?

**Comment by teodors** [comment]
Thanks for quick response. I'll try to do it soon.

**Comment by jsor** [comment]
Closing for now, feel free to reopen if needed.
