### ISSUE TITLE
Need responsive carousel with onclick arrows to get ajax content.

### ISSUE THREAD

**Issue by mpkumar87** [jsor/jcarousel#751]
Hi,
Need to get responsive carousel with inital content. if no more content in the slide, then need to call ajax to append to the slider.. Please guide me to solve this problem..

Thanks,
Premkumar M

**Comment by jsor** [comment]
Nope.

**Comment by mpkumar87** [comment]
Hi,
is it not possible to combine responsive with ajax call..

Thanks,
Premkumar M
