### ISSUE TITLE
Bootstrap / Jquery

### ISSUE THREAD

**Issue by newseed** [jsor/jcarousel#754]
I have an issue with the jcarousel for the new store upgrade. The old store uses jquery 1.5.1 whereas the new version uses 1.10.1. which now breaks the carousel.

Here's the link: http://www.thewirehorse.com/default-v5.asp

I verified that it is the jquery causing the carousel to stop working by swapping the new version with the old one.  However, the new store has various functions that requires 1.10.1 version.

Is there a fix for this?  I applied the latest jquery.jcarousel.js file from here (0.3.3) dated 2/28/2015 but it did not work.

Any help would be greatly appreciated.

**Comment by jsor** [comment]
If you upgrade jQuery from 1.5.1, you most likeley used jCarousel 0.2 before (as jCarousel 0.3 requires at least jQuery 1.7).

jCarousel 0.2 should work with jQuery 1.10. Are you sure that it is jCarousel which doesn't work. I see an error in the console, but it comes from another plugin (jquery.customScroller-1.2.js). Have you tried to use the [jQuery migrate plugin](https://github.com/jquery/jquery-migrate/)?

**Comment by newseed** [comment]
Thanks for quick replay.

I went ahead and create a second page. First one works using an older version of jquery.
http://www.thewirehorse.com/default-v5test.asp

The second one does NOT work. It uses the 1.10.1 jquery.
http://www.thewirehorse.com/default-v5test-2.asp

Per the second link, I commented out that customscroller.  I aslo added the jquery migrate script but still no change.

**Comment by newseed** [comment]
Update:  I went directly to your sample files you have and check to make sure they work which they did and so I then changed the default jquery library you had to 1.10.1 and it quit working.
http://www.thewirehorse.com/storev5/pc/scripts/jcarousel/examples/static_simple.html

**Comment by jsor** [comment]
You've included both jCarousel 0.3 **and** 0.2. You should remove version [0.3](http://www.thewirehorse.com/storev5/pc/scripts/jcarousel/lib/jquery.jcarousel.js) (it is also included **before** jQuery)

**Comment by newseed** [comment]
I've stripped out just about everything leaving the jquery and jacarousel stuff.
http://www.thewirehorse.com/default-v5test-3.asp
Also, I did not if you missed my last comment or not this does work either.
http://www.thewirehorse.com/storev5/pc/scripts/jcarousel/examples/static_simple.html
I basically swap the jquery over to 1.10.1

**Comment by jsor** [comment]
jCarousel works on http://www.thewirehorse.com/default-v5test-3.asp or do i miss something? On http://www.thewirehorse.com/storev5/pc/scripts/jcarousel/examples/static_simple.html, you're missing the jQuery migrate plugin.

**Comment by newseed** [comment]
No you are not missing something. I did not have the migrate tool in the right place which should have been right after the jquery 1.10.1 file

**Comment by newseed** [comment]
Update: Works fine in IE and Chrome but not FF. Can you verify that for me?

**Comment by newseed** [comment]
Update: Never mind. I closed my FF session and restarted. All is fine now.  Thank you so much for helping me resolve the issue.  One question, can I add the css and js file to use with the 2.0 version?

**Comment by jsor** [comment]
Yes, just keep all jCarousel files.

**Comment by newseed** [comment]
Thank you.
