### ISSUE TITLE
Make carousel swipeable?

### ISSUE THREAD

**Issue by jamminjames** [jsor/jcarousel#755]
I saw in a closed comment thread where you suggested using touchswipe with jcarousel. I tried that, but still can't get it to swipe.

I have both scripts called in the head, and tried what you suggested in the body, as well as some other things. My inner div id="carousel" and class="jcarousel", and this is what I have for the function in the body:
```
<script>
$(document).ready(function() {
	var carousel.jcarousel();
	carousel
    .touchwipe({
        wipeLeft: function() {
            carousel.jcarousel('next');
        },
        wipeRight: function() {
            carousel.jcarousel('prev');
        }
    });
</script> 	
```

I also tried something else I found:

```
<script>
$(document).ready(function() {
	$('#carousel').cycle({
		timeout: 0,
		fx: 'scrollHorz',
		next: '#next',
		prev: '#prev' 
	});
 
	$("#carousel").touchwipe({
 		wipeLeft: function() {
 	 		$("#carousel").cycle("next");
 		},
 		wipeRight: function() {
 	 		$("#carousel").cycle("prev");
 		}
	});
});
</script> 	
```

...but nothing's working. Please help. Thanks!

**Comment by jsor** [comment]
Please setup a reprocuible test-case with everything you have so far.

**Comment by jamminjames** [comment]
How do I set that up? The only thing I didn't include in the above is the trigger code (or whatever you call it) in the body. I tried several different things, as I tried to include above, but looking at it now, it seems that didn't post. I don't see how to include code on this forum, so I'll attach this screenshot of it:

![corel924](https://cloud.githubusercontent.com/assets/7809762/7032091/23558cbc-dd25-11e4-9158-509d91066984.jpg)

**Comment by jsor** [comment]
You're mixing in some code from another plugin (jQuery Cycle). Have you tride this: https://alexbudeanu.wordpress.com/2012/11/11/adding-swipe-to-jcarousel/

For reproducibe test-cases, use [jsfiddle](http://jsfiddle.net) or [codepen](http://codepen.io).

**Comment by jamminjames** [comment]
I just tried that, still not working. I have the carousel inside a wrapping div, like so:
<div id="carousel-wrap" class="jcarousel-wrapper">
     <div id="carousel" class="jcarousel">
        <ul>
          <li><a href="images/HT-cover-1.jpg"><img src="images/HT-cover-1-sm.jpg" alt="Humor Times covers" /></a></li>
          <li><a href="images/HT-cover-2.jpg"><img src="images/HT-cover-2-sm.jpg" alt="Humor Times covers" /></a></li>
           <li><a href="images/HT-cover-3.jpg"><img src="images/HT-cover-3-sm.jpg" alt="Humor Times covers" /></a></li>
           <li><a href="images/HT-cover-4.jpg"><img src="images/HT-cover-4-sm.jpg" alt="Humor Times covers" /></a></li>
           <li><a href="images/HT-cover-5.jpg"><img src="images/HT-cover-5-sm.jpg" alt="Humor Times covers" /></a></li>
           <li><a href="images/HT-cover-6.jpg"><img src="images/HT-cover-6-sm.jpg" alt="Humor Times covers" /></a></li>
           </ul>
    </div>
     <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
     <a href="#" class="jcarousel-control-next">&rsaquo;</a>
     <p class="jcarousel-pagination"></p>
</div>

... would that cause a problem?

**Comment by jsor** [comment]
Can you please setup a reproducibe test-cases on [jsfiddle](http://jsfiddle.net) or [codepen](http://codepen.io).
