### ISSUE TITLE
pagination with individual text instead of page numbers

### ISSUE THREAD

**Issue by giukra96** [jsor/jcarousel#757]
Is it possible to set the pictures name as the navigation text resp. the pagination text? if yes, how can I achieve this?
I am working with the swiss desktop cms "weblica" but they do not have an option for a slider like yours.

**Comment by jsor** [comment]
You can use the [`item`](http://sorgalla.com/jcarousel/docs/plugins/pagination/reference/configuration.html#item) options to control the markup of the pagination links. The second `carouselItems` is a jQuery object containing the carousel items of the current page.

Example:
```javascript
$('.jcarousel-pagination').jcarouselPagination({
    item: function(page, carouselItems) {
        return '<li><a href="#' + page + '">' + carouselItems.eq(0).attr('title') + '</a></li>';
    }
});
```
