### ISSUE TITLE
Pagination issue that is on last page

### ISSUE THREAD

**Issue by enkhsaruul** [jsor/jcarousel#759]
Hello,

I am using pagination plugin with horizontal css. I want to show 3 items per page at most. When I click on last page it shows 3 items including previous page items. What I want is that to see remained item/items. 
For example: if there are 5 items(let say i1, i2, i3, i4, i5), I would like to see 3 items (i1, i2, i3) at first page and only 2 items (i4, i5) in the second page. 
Now it shows 3 items (i1, i2, i3) at first page and 3 items (i3, i4, i5) in the second page. 
I put height and width on li as well. It did not affect well.
Please advise me to fix this issue.

Thanks,
Saruul

**Comment by jsor** [comment]
That is not possible with jCarousel. It's actually a feature of jCarousel to not have empty space and always show as much items as possible.

**Comment by enkhsaruul** [comment]
I see. Thanks for your prompt reply!
