### ISSUE TITLE
Autoscroll works 10% of the time

### ISSUE THREAD

**Issue by lackzinsky** [jsor/jcarousel#762]
Hi Jsor/community,

First of all, I wish to congratulate the creator of jcarousel. This is a very useful component to add meeting the needs of many developers.

I've been using several features of jcarousel successfully, but I face a problem when trying to integrate autoscroll plus responsiveness. I've created a Jsfiddle illustrating the problem. Only around 1/10th of the time the autoscroll works and I get no error message in my browser's console. I've tried different browsers and I've googled/checked the issues thread. I've tried version 0.3 of jcarousel and up. Would someone be able to have a look at the fiddle and identify where the error is?
https://jsfiddle.net/vec6rum4/

Thanks in advance

**Comment by jsor** [comment]
Unfortunately, i cannot reproduce this. I've tried this in several browser and it worked everytime.

**Comment by lackzinsky** [comment]
I see, could it be due to me using angularjs and ng-repeat to create the li elements?

**Comment by jsor** [comment]
Most probably, yes. You should ensure, that the initialization of the carousel happens after the html is generated.
