### ISSUE TITLE
how can I get the  initial  index of the current target

### ISSUE THREAD

**Issue by zjafei** [jsor/jcarousel#766]
Result like this 
![qq 20150703093141](https://cloud.githubusercontent.com/assets/8189405/8491093/bf683688-2166-11e5-8802-545de097dbec.jpg)

I use 
`$('#jcarousel').jcarousel('target').index();`
but not work right 
I look the source code find Pagination Plugin can get the current page, but this Plugin must work with some element and create some elements. I don't want to do that. so could you tell me how can I get the  initial  index of the current target just with jCarousel core code??
good luck happy work

**Comment by jsor** [comment]
This should work. But hard to say without actually seeing some code. You probably need to call this method in an event handler, eq. on [`createend`](http://sorgalla.com/jcarousel/docs/reference/events.html#createend).

**Comment by zjafei** [comment]
ok thx
