### ISSUE TITLE
autoscroll stops at final element

### ISSUE THREAD

**Issue by buddikastay** [jsor/jcarousel#767]
Hi,

I love the Jcarousel. It works like a charm. I have a small issue. When autoscrolling is enabled, it auto scroll elements just fine. but when it reach to the last element, it stops there. Its not replaying again. is re-playing is not available in the plugin? Thanks for the support.

**Comment by jsor** [comment]
Set `wrap: 'circular'`, see http://sorgalla.com/jcarousel/docs/reference/configuration.html#wrap

**Comment by buddikastay** [comment]
Thanks for the reply Jsor! i tried it like this:
.jcarouselAutoscroll({
            interval: 3000,
            target: '+=1',
            autostart: true,
            wrap: 'circular'
        });

But no luck still. Am i doing it in a wrong way? Let me know.

**Comment by jsor** [comment]
This is an option for the carousel:

```javascript
.jcarousel({
    wrap: 'circular'
})
.jcarouselAutoscroll({
    interval: 3000,
    target: '+=1',
    autostart: true
});
```

**Comment by buddikastay** [comment]
Wow, amazing dude! it worked like a charm. Thanks for the big help. Jcarousel rocks!

**Comment by fidoboy** [comment]
I've configured exactly this way and it still doesn't work. It stops in last item. wrap parameter is set to 'circular' obviously.

**Comment by fidoboy** [comment]
If I set wrap to 'last' it works. The carousel rewinds to first item and it starts again, but circular is not working... :cry:

**Comment by jsor** [comment]
Could you please setup a reproducible testcase somewhere?

**Comment by fidoboy** [comment]
I can't sorry. But after some testing, no it works, I'm not sure why... But it's not circular, it works the same way than 'last', when autoscroll reach the last item, it rewinds all the way to the beginning 😁
