### ISSUE TITLE
Vertical scroll with two columns

### ISSUE THREAD

**Issue by stillfire** [jsor/jcarousel#769]
Hey, is there any way to do a vertical scroll with two columns of list items?

The ul  is twice the size it should be so it keeps scrolling with a bunch of empty space.

Thanks.

**Comment by jsor** [comment]
No, sorry. The only way is to have something like

```html
<ul>
  <li>
    <img src="img1.jpg">
    <img src="img2.jpg">
  </li>
  <li>
    <img src="img3.jpg">
    <img src="img4.jpg">
  </li>
</ul>
```
