### ISSUE TITLE
jCarousel on Wordpress?

### ISSUE THREAD

**Issue by mattrice92** [jsor/jcarousel#770]
Hey there,

Not sure how much support you offer for Wordpress issues, so I totally understand if this is out of your scope, but here's my problem:

I'm trying to implement jCarousel on a Wordpress site that I'm working on, and while I have a working JSFiddle of it (https://jsfiddle.net/mattrice92/0acejn9d/9/), the exact same code doesn't work on Wordpress (markup and CSS do - script does not). I understand that Wordpress uses slightly different syntax, but I'm not confident enough in my jQuery knowledge to attempt to fix it myself any further than I already have.

For reference, we're on Wordpress 4.2.2, X theme 4.0.4 with the Cornerstone 1.0.3 page builder. I'm using the jQuery Updater plugin to keep us on the latest jQuery. Markup is in a raw HTML container, CSS and jQuery are in the custom fields in Cornerstone (though I've also tried hosting/linking an external JS file, to no avail).

If you've got any insight to this at all, it'd be greatly appreciated, but thanks either way for reading through this!

Matt

**Comment by jsor** [comment]
Can't say much without seeing the actual setup. Do you have a URL or something where i can see this?

**Comment by mattrice92** [comment]
Sorry to leave this hanging - missed the email notification. But I did figure it out. I just linked the JS file in my footer file rather than the header. Guess it was just trying to execute before my sliding content had loaded. Just wanted to update for anyone who might be having the same problem, and thank for the plugin, it works great!

**Comment by jsor** [comment]
Thanks for the feedback, glad you solved it.
