### ISSUE TITLE
Background change

### ISSUE THREAD

**Issue by lpguedes** [jsor/jcarousel#771]
Hi!

It's possible to change the background image (or some div background) when the image of the carousel changes?

My objective is use a specific background to a specific image in the carousel, and when the image change in carousel, the background changes too.

I found the _animate function and configured to return an alert message when the routine pass that way. At the same time I inserted an attribute called data-bg-image in the li tag, and this attribute is the path to the background I need to show.

Is there any way to do that?

Thanks!

**Comment by jsor** [comment]
Yes, you can use the [`targetin`](http://sorgalla.com/jcarousel/docs/reference/events.html#targetin) item event:

```javascript
$('.jcarousel').on('jcarousel:targetin', 'li', function() {
    var bgImage = $(this).data('bg-image');
    // Do something with bgImage
});
```

**Comment by lpguedes** [comment]
Thank you, jsor!
