### ISSUE TITLE
Event on image click

### ISSUE THREAD

**Issue by lpguedes** [jsor/jcarousel#773]
Hi again!

Sorry to bother you again, but I believe will be the last time ...

I wonder if it is possible to trigger some kind of event (such as a image zoom plugin or similar, for example), when you click on it.

You can use this type of event?

A hug

Thanks!

**Comment by jsor** [comment]
This is out of the scope of jCarousel, just use plain jQuery events:

```javascript
$('.jcarousel').on('click', 'img', function() {
   // Do something
});
```
