### ISSUE TITLE
Scrolling does not work on Chrome iOS

### ISSUE THREAD

**Issue by estockwellalpert** [jsor/jcarousel#775]
The carousel does not scroll on Chrome on my iPhone. It works on Safari and on all desktop browsers, but on Chrome, the left/right arrows do nothing; the image does not move.

**Comment by estockwellalpert** [comment]
Has anybody been made aware of this issue?

**Comment by jsor** [comment]
I'm not aware of this and can't reproduce this. I tested the carousel on http://sorgalla.com/jcarousel/ and it works as expected.

**Comment by estockwellalpert** [comment]
Could you please look at it on my site http://qa.msdonline.com then and let me know what's wrong with it? The left/right arrows are hidden but it has pagination buttons and I added swipe functionality. It works on Safari but not Chrome on the iPhone.

**Comment by estockwellalpert** [comment]
Actually, this page http://54.144.148.151/ is the most recent version of my site. I was using custom pagination but I replaced it with jcarousel's pagination, but it still does not work.

**Comment by jsor** [comment]
Yes, indeed, i checked it in Chrome on iOS and something seems to be wrong. Unfortunately i wasn't able to debug it. So, unfortunatly i can't help much here, sorry.

**Comment by Blainegunn** [comment]
I just patched it like so:
```
    if(window.chrome){
      var carouselBox = $('.jcarousel-box');
      var leftRight = 0;
      document.getElementsByClassName('jcarousel-next')[0].onclick = function(){
        if(leftRight < -550){
          return;
        }else{
          leftRight = leftRight - 110.2;
          carouselBox.animate({
            left: leftRight
          }, 500);
        }
      };
      document.getElementsByClassName('jcarousel-prev')[0].onclick = function(){
        console.log(leftRight);
        if(leftRight > -110.2){
          return;
        }else{
          leftRight = leftRight + 110.2;
          carouselBox.animate({
            left: leftRight
          }, 500);
        }
      };
    };
```
