### ISSUE TITLE
reload method not working

### ISSUE THREAD

**Issue by redonditodericota** [jsor/jcarousel#777]
Hi. I am using jcarousel responsive plugin, which has this code:

        jcarousel.on('jcarousel:reload, jcarousel:create', function () {
          console.log('reloading carousel');
          var carousel = $(this),
  				width = carousel.innerWidth();
  				cantSlides = 1;
  				if (width >= 1600){
  					width = width / 4;
  					cantSlides = 4;
  				}else if (width >= 1200) {
  					width = width / 3;
  					cantSlides = 3;
  				}else if (width >= 800) {
  					width = width / 2;
  					cantSlides = 2;
  				}
  				carousel.jcarousel('items').css('width', Math.ceil(width) + 'px');
  				
  				$('.jcarousel-control-prev')
  				.jcarouselControl({
  					target: '-='+cantSlides
  				});
  
  				$('.jcarousel-control-next')
  				.jcarouselControl({
  					target: '+='+cantSlides
          });

        })

This works great when the window is loaded (F5), but I can't get the reload event to fire. Here:

    $(window).resize(function(){
      $('.jcarousel').jcarousel('reload');//This does not fire the above function. Why?
    });

**Comment by jsor** [comment]
Multiple events must be separated by a space, not by a comma.

Correct
```
jcarousel.on('jcarousel:reload jcarousel:create', function () {
```
Wrong
```
jcarousel.on('jcarousel:reload, jcarousel:create', function () {
```

**Comment by redonditodericota** [comment]
Thank you! It works like a charm now.
