### ISSUE TITLE
center:true with wrap:"circular" on horizontal carousel 

### ISSUE THREAD

**Issue by fishnyc22** [jsor/jcarousel#778]
Hey there. Been a long time fan of jcarousel. Thanks for all the great work. 

I have a horizontal carousel that has a single (large font) word in each LI tag. I want those words across width of the page with the selected word centered on the screen. I have center:true and  wrap:"circular" set. 

My problem is that the left side of the carousel does not fill in to fill the words on the left side of the screen as it scrolls using PREV. For example, if I click NEXT it appears infinite. But if I click PREV, when the first word reaches the center there are no words to its left.  to fill the space. If I click PREV again, a new word appears quickly. 

if I don't use "center:true" then it works great b/c it never shows a gap to the left but the problem is that I need the word to be centered on the screen. Is there any way to make this work properly? Thank you!

Dave

**Comment by jsor** [comment]
I'm afraid that isn't possible with jCarousel. As noted in the docs, the `center` is marked as experimental and will not work in all setups.
