### ISSUE TITLE
JS error in Console: Unable to get property 'left' of undefined or null reference only IE but not in FF or Chrome

### ISSUE THREAD

**Issue by deyan-enchev** [jsor/jcarousel#781]
The error will appear based on the following:

If not page is post back, zooming in and out of the browser or resizing the browser's window does not produce the error.
But after a post back (be it from a button click event or what so), zooming in and out of the browser or resizing the browser's window will produce the error.

This problem only occurs in IE, but not in FF or Chrome.

Steps to reproduce:
1. Reload a page the contains the carousel
2. Resize the page in IE

The issue is straight forward to replicate.

![2015-11-18_1046](https://cloud.githubusercontent.com/assets/12510934/11236371/bcd1ff7a-8de1-11e5-9d94-d62f3dfcec5d.png)

**Comment by jsor** [comment]
Can you setup a reproducible test case somewhere (ie. on jsfiddle)?

**Comment by deyan-enchev** [comment]
I am afraid that a reproduction cannot be made in isolated environment such as: https://jsfiddle.net/vdvo0j2L/ 

Surely the problem is more deep than simply putting a jcarousel on a page.
The issue itself can be seen after POST request is executed on page opened in IE that contains the jcarousel.

Best,
Deyan

**Comment by jsor** [comment]
It's hard to say without actually seeing the code. I supect that the element you assigned the carousel to is removed from the DOM and/or maybe replace by another element. So, jCarousel loses the reference to the actual DOM element.

```javascript
var element = $('.jcarousel').jcarousel();
```

I guess that after the POST request the DOM element store in `element` isn't anymore in the DOM.
