### ISSUE TITLE
trouble initializing jcarousel

### ISSUE THREAD

**Issue by mdw** [jsor/jcarousel#782]
I'm using the _basic_ pattern but my event handlers don't get attached to the prev and next buttons. Error in console after loading page says, `TypeError: a(...).on is not a function` which I think means a conflict with the $ symbol?

I'm loading my simple script with click handlers for prev and next buttons after all other JS, including jquery, and it's wrapped in a $(document).ready(function(){ }); I also tried wrapping the initialization and setting the `prev` and `next` click handlers inside a block as you did in `jcarousel.basic.js` to avoid conflicts.

Thing is, if I do this manually, everything works fine, i.e. at the console:

	$('.jcarousel-next').click(function(e){ 
		e.preventDefault(); 
		$(".jcarousel").jcarousel('scroll', '+=4'); 
	});

the handler gets registered and clicking results in scrolling by 4. I'm using this HTML, as in the examples:

	<a href="#" class="jcarousel-prev">&lsaquo;</a>
	<a href="#" class="jcarousel-next">&rsaquo;</a>

**Comment by jsor** [comment]
You probably load jQuery after the jCarousel scripts in your page. To say more, i have to see the actual code.
