### ISSUE TITLE
Slider infinite

### ISSUE THREAD

**Issue by zabuza225** [jsor/jcarousel#785]
Hello, 
how  silder infinite with Jcarousel-connected

**Comment by snake-345** [comment]
You need set wrap: 'circular'
Example:
Conected carousels
``` javascript
// Setup the carousels. Adjust the options for both carousels here.
var carouselStage      = $('.carousel-stage').jcarousel({wrap: 'circular'}).jcarouselSwipe();
var carouselNavigation = $('.carousel-navigation').jcarousel().jcarouselSwipe();
```

**Comment by zabuza225** [comment]
thank you so much

the very works well but without the .jcarouselSwipe ();
var carouselStage      = $('.carousel-stage').jcarousel({wrap: 'circular'});
var carouselNavigation = $('.carousel-navigation').jcarousel();

**Comment by snake-345** [comment]
Oh sorry. I'm copy it code from my reppsitory)

**Comment by zabuza225** [comment]
ok +1
