### ISSUE TITLE
gallery not starting from ajax reload

### ISSUE THREAD

**Issue by tlonero** [jsor/jcarousel#787]
sending  request via php script from ajax  $.ajax({		type: "POST",
		url: "/includes/gallery.php", Result comes back fine with photo's and css but the 
problem is that it comes back but how would you reload the jquery.jcarousel.min.js ?

thanks

**Comment by snake-345** [comment]
if jcarousel initialized then you may call $('.jcarousel').jcarousel('reload').
if jcarousel not initialized then you should initialize it after ajax

**Comment by tlonero** [comment]
hi snake this is the page
http://www.exclusivepaperbags.com/jcart/products/express_flexo.php
choose format 18x8x25 the first one
choose Quantità
then below Colore Fondo click on white, now this is where ajax goes and uses the jcarousel to load 
Stampa Flexografica choose 1 color now it calls ajax
the pictures of the colors associated with white which are five. 

$.ajax({
		type: "POST",
		url: "/includes/offsetc.php",
success: function(data){
			
			
			
			$("#mycarouseltwo").html(data);
			$('#mycarouseltwo').jcarousel('reload', {
    animation: 'slow'
}


);
this is the code I was using but still not working

thanks tony

**Comment by snake-345** [comment]
Looks like you use old version jcarousel. Can you update it?

**Comment by tlonero** [comment]
ok

**Comment by tlonero** [comment]
downloaded the jcarousel-master from here and updated the jquery.jcarousel.js and jquery.jcarousel.min.js

**Comment by tlonero** [comment]
now the above gallery is not working after I updated the above files

**Comment by snake-345** [comment]
Now you should look documentation and edit you code. In new version was make significant changes.
http://sorgalla.com/jcarousel/examples/ajax/ it example about reload jcarousel after ajax

**Comment by jsor** [comment]
Closing for now, feel free to reopen if needed.
