### ISSUE TITLE
Sliding with 2 elements only

### ISSUE THREAD

**Issue by thecheshirecat** [jsor/jcarousel#789]
I found an issue while scrolling with "next" button when there are only 2 items in the carousel.

The thing is, that when I have only two items, the first time I click the "next" button to slide to the following item, this one won't move the width it should. But then, if I return to the first one, and try again to go the second item, this will works properly.
Mention that, with 3 or more items, the issue I just described it doesn't happens, only when there are two items.

Tried version 0.3.3 and 0.3.4.

**Comment by jsor** [comment]
Hi,

sorry for the late response. Could you setup a reproducible test case?
