### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by ajgor11** [jsor/jcarousel#791]
Hi, i'm using feature slider

https://github.com/jsor/jcarousel/tree/91b1616fab0e3dfbdb8f39e42f39c48cbe6000d6/examples/feature_slider

It's work perfectly, but i can't install autoscroll:

My Code:
`jQuery(function() {

$('#mycarousel')
    .jcarousel({
        start: 5,
        scroll: 1,
      wrap: 'circular'
    })
    .jcarouselAutoscroll({
        interval: 1000
    });
});`

When I change jcarousel.min to jcarousel script stop working.

Can you help me?

**Comment by jsor** [comment]
The example is for version 0.2 which isn't compatible with the latest 0.3.
