### ISSUE TITLE
Issue with border around list in aspx page 

### ISSUE THREAD

**Issue by jmartin405** [jsor/jcarousel#792]
I have jcarousel working in a visual studio .net website with the exception of a black border around the text area(overkill but just using it to scroll text on a website). I have spent several hours trying to figure out where this box is coming from. I am sure this is a simple question/issue just at a loss what to try.

Any assistance is appreciated.

Thanks

**Comment by jsor** [comment]
Most probably from the border is produced by any CSS styling (or the lack of). Have you checked the styles from your browser developer console?
