### ISSUE TITLE
Tabs sliding problem

### ISSUE THREAD

**Issue by vrinceanuv** [jsor/jcarousel#793]
If i use the slider in multiple places in 1 page using tabs. When i click on a tab and i make that visible, when i click the next button of the slider it goes 2 slides next and after that as it should, any ideas?

Thank you

**Comment by snake-345** [comment]
Can you show code or site which have this problem?

**Comment by vrinceanuv** [comment]
http://vrinceanu.com/jslider/

Click tab 2 and click on gallery next image and you see that it goes 2 images at first, but after it works ok.

**Comment by snake-345** [comment]
I see problem. This is due to the fact that the slider is initialized with display: none. I'll see what can be done. 
Till you can to initialize the slider after the tab was showed.
Example:
``` javascript
$(document).ready(function () {
    function showTab(tab) {
        var jcarousel = tab.find('[data-jcarousel]');
        tab.show();

        if (!$.isPlainObject(jcarousel.data('jcarousel'))) {
            jcarousel.each(function() {
                var el = $(this);
                el.jcarousel(el.data());
            });


            tab.find('[data-jcarousel-control]').each(function() {
                var el = $(this);
                el.jcarouselControl(el.data());
            });
        }
    }
    
    showTab($('.tab1'));

    $('.tab1-show').on('click', function () {
        showTab($('.tab1'))
        $('.tab2').hide();
    });

    $('.tab2-show').on('click', function () {
        $('.tab1').hide();
        showTab($('.tab2'))
    });
});
```

**Comment by vrinceanuv** [comment]
Will try that, thanks for trying to help. This applies to modals as well, just to give another example of the same root problem. Thanks again

**Comment by vrinceanuv** [comment]
@snake-345 Added what you told me to, now the problem appears from the start, no need to go to another tab, which is not working anymore though(not to worry about).

http://vrinceanu.com/jslider/#

**Comment by snake-345** [comment]
use 
``` javascript
showTab($('.tab1'));
```
instead
``` javascript
$('.tab1').show();
```

**Comment by snake-345** [comment]
and you should send jQuery object in showTab function instead string

**Comment by vrinceanuv** [comment]
@snake-345 I was too tired and wrote the bad code, now tabs work, the thing is this is replicating for the displayed tab even if i applied your piece of code.

http://vrinceanu.com/jslider/

**Comment by snake-345** [comment]
Man, just copy-paste my code pls. Fully. I see the difference between my code and your code.

**Comment by vrinceanuv** [comment]
@snake-345 It worked. I realised i need to sleep more though. Thank you for the help provided.
