### ISSUE TITLE
Images is not load on IE & Edge 

### ISSUE THREAD

**Issue by mastercho** [jsor/jcarousel#794]
https://github.com/jsor/jcarousel/issues/527

As described in reference is not working still. Is soon any updates about that?

**Comment by snake-345** [comment]
Hi. I check carousel on this page http://sorgalla.com/jcarousel/ in ie9 and image loaded always. Could you setup a reproducible test case?

**Comment by mastercho** [comment]
Code is massive, you can see here :
http://bit.ly/1Umvluw
you can see mostly when you try with different IE versions.

**Comment by mastercho** [comment]
Ok seems IE issue stays...

**Comment by snake-345** [comment]
Sorry but your site not opened in IE. I could not even see it in IE. But i see in chrome and most likely a problem in your code that dynamically loads images.
