### ISSUE TITLE
Vertical Thumbnails 

### ISSUE THREAD

**Issue by Git987886** [jsor/jcarousel#797]
I'm trying to change thumbnails to vertical , 
Is it possible to do that?

**Comment by jsor** [comment]
Yes, see

* http://sorgalla.com/jcarousel/examples/vertical/
* https://github.com/jsor/jcarousel/tree/master/examples/vertical
* http://sorgalla.com/jcarousel/docs/reference/configuration.html#vertical

**Comment by Git987886** [comment]
I'm afraid not, I'm talking about vertical thumbnails, like this : 
• http://www.menucool.com/slider/thumbnail-slider-demo-3
• https://amazingslider.com/examples/jquery-gallery-with-vertical-thumbnails-id28/

**Comment by jsor** [comment]
Yes, you can use the [vertical carousel](http://sorgalla.com/jcarousel/examples/vertical/) as a starting point and adjust the placement of the prev/next buttons via css.

**Comment by Git987886** [comment]
<img width="852" alt="capture d ecran 2016-04-14 a 03 59 00" src="https://cloud.githubusercontent.com/assets/18240621/14514911/46ca1726-01f5-11e6-8d06-5a86b285ea4f.png">
I tried to change buttons position but I'm not qualified to do that... I need to have the exact thumbnails positions like this screenshot. Could you help me?

**Comment by Git987886** [comment]
Here's the page http://lespetiteschaudieres.com/index.php/robe-jupe-rayee-noir-rouge.html

**Comment by jsor** [comment]
The carousel uses [bxslider](http://bxslider.com), not jCarousel. Not sure i can help here ;)

**Comment by Git987886** [comment]
Ah ok, sorry! Because I fond this class="jcarousel jcarousel-skin-tango thumb-vertscroller
