### ISSUE TITLE
Scaled down images in Jcarousel

### ISSUE THREAD

**Issue by jforjava1981** [jsor/jcarousel#801]
I am using basic version of Jcarousel, I want to use scaled down versions of images in jcaraousel without using fixed height and width. I will be using 200px as max width for each scaled down image. I am not able to fix this as I am not a CSS expert. Please find below code i am using 
  [id^=caraouselimageContainer_] {
    	max-width: 200px;
    }
  [id^=caraouselimageContainer_] img{
    	max-width:100%;
  		max-height:200px;
  		width: auto;
  		height: auto;
    }

		<div class="jcarousel-wrapper">
                <div class="jcarousel">
                    <ul>
                         <c:forEach var="itemImageDTO" items="${item.itemImageDTOList}" varStatus="cnt">
							<li><div id="caraouselimageContainer_${cnt}">
									<img  src="${pageContext.request.contextPath}${imgItemPath}/${itemImageDTO.itemImageNameOnServer}"></img>
								</div>
							</li>	
                        </c:forEach>
                    </ul>
                </div>
                <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                <a href="#" class="jcarousel-control-next">&rsaquo;</a>
             </div> 
Can you please help me with this ?
![scaled_down_images](https://cloud.githubusercontent.com/assets/5867866/15292909/155f5ec2-1ba3-11e6-95ab-259d577cff24.PNG)

**Comment by jforjava1981** [comment]
Was able to resolve this. there were some problem in my config, i was setting it vertical as true

**Comment by jforjava1981** [comment]
Here is the modification I did :

.jcarousel-wrapper{
        height:auto;
    }
    
    .jcarousel li{
       margin: 5px;
    }
    
   .jcarousel-control-prev, .jcarousel-control-next {
          top:40px;
   }

**Comment by snake-345** [comment]
Do you have a link to an example? Maybe you can setup it on codepen?

**Comment by jforjava1981** [comment]
Will try to set it up today
