### ISSUE TITLE
Autoplay responsive slider

### ISSUE THREAD

**Issue by talent74** [jsor/jcarousel#802]
http://sorgalla.com/jcarousel/examples/responsive/

How would you make this auto play on page load, pause on rollover, change the speed etc..?

**Comment by jsor** [comment]
You can use the autoscroll plugin: http://sorgalla.com/jcarousel/docs/plugins/autoscroll/

See this issue comment on how to stop/start autoscroling on hover: https://github.com/jsor/jcarousel/issues/353#issuecomment-4766529

**Comment by talent74** [comment]
Avoiding any use of plugins, what do I need to add to the following responsive.js?
`
(function($) {
$(function() {
var jcarousel = $('div.slider');

    jcarousel
        .on('jcarousel:reload jcarousel:create', function () {
            var carousel = $(this),
                width = carousel.innerWidth();

            if (width >= 900) {
                width = width / 4;
            } else if (width >= 600) {
                width = width / 3;
            } else if (width >= 350) {
                width = width / 2;
            }

            carousel.jcarousel('items').css('width', Math.ceil(width) + 'px');
        })
        .jcarousel({
            wrap: 'circular'
        });

    $('.prev')
        .jcarouselControl({
            target: '-=1'
        });

    $('.next')
        .jcarouselControl({
            target: '+=1'
        });

    $('.jcarousel-pagination')
        .on('jcarouselpagination:active', 'a', function() {
            $(this).addClass('active');
        })
        .on('jcarouselpagination:inactive', 'a', function() {
            $(this).removeClass('active');
        })
        .on('click', function(e) {
            e.preventDefault();
        })
        .jcarouselPagination({
            perPage: 1,
            item: function(page) {
                return '<a href="#' + page + '">' + page + '</a>';
        }

    });
});
})(jQuery);
`

**Comment by talent74** [comment]
I tried adding:
`		$('div.slider')
			.jcarousel()

			.jcarouselAutoscroll()
			.hover(function() {
				$(this).jcarouselAutoscroll('stop');
			}, function() {
        		$(this).jcarouselAutoscroll('start');
			});`

**Comment by talent74** [comment]
BTW the link: http://sorgalla.com/projects/jcarousel/examples/static_auto.html raises 404 not found, not sure if you are aware of this

**Comment by jsor** [comment]
Do you get any errors? The code looks correct.

> BTW the link: http://sorgalla.com/projects/jcarousel/examples/static_auto.html raises 404 not found, not sure if you are aware of this

Yes, that used to be the docs for the old 0.2 version. The new docs are at http://sorgalla.com/jcarousel/docs/plugins/autoscroll/

**Comment by talent74** [comment]
Yes, sorry I should have included...
Uncaught SyntaxError: Unexpected token .

**Comment by jsor** [comment]
If you could provide a reproducible test case i could have a look at it.

**Comment by talent74** [comment]
Great thanks! I'll add to a server, it's on my local set up right now, bear with me...

**Comment by talent74** [comment]
Here you go: http://www.fabjungphotography.com/jcarousel/jcarousel.html

I am seeing a different error now... Uncaught SyntaxError: Unexpected identifier

**Comment by jsor** [comment]
There is a missing `});`here

```js
            .jcarouselPagination({
                perPage: 1,
                item: function(page) {
                    return '<a href="#' + page + '">' + page + '</a>';
            } // <---

            $('div.slider')
```

Correct:
```js
            .jcarouselPagination({
                perPage: 1,
                item: function(page) {
                    return '<a href="#' + page + '">' + page + '</a>';
            });

            $('div.slider')
```

**Comment by talent74** [comment]
Actually, that didn't do it, but it did help me see I had put it in the wrong place.

correct:
`
            }

        });

		$('div.slider')
			.jcarousel()
			.jcarouselAutoscroll()
			.hover(function() {
				$(this).jcarouselAutoscroll('stop');
			}, function() {
				$(this).jcarouselAutoscroll('start');
			});`

**Comment by talent74** [comment]
Thanks for your help on the autoplay(scroll). Any ideas how to adjust the speed and easing?

**Comment by jsor** [comment]
See the docs:
http://sorgalla.com/jcarousel/docs/plugins/autoscroll/reference/configuration.html#interval
http://sorgalla.com/jcarousel/docs/reference/configuration.html#animation

**Comment by talent74** [comment]
Thanks again, I'll take a look
