### ISSUE TITLE
Is it possible make the fade version of jcarousel be the autostart to fade effect?

### ISSUE THREAD

**Issue by wilsontse88** [jsor/jcarousel#806]
Is it possible make the fade version of jcarousel be the autostart to fade effect?

**Comment by snake-345** [comment]
you can try [jcarouselFade plugin](https://github.com/snake-345/jcarouselFade)

**Comment by wilsontse88** [comment]
i'm using it, but it cannot be the autostart the fade effect. can it auto start the fade animation?

**Comment by snake-345** [comment]
you mean fade animation when carousel initialized? or fade animation with jcarouselAutoscroll plugin?

**Comment by wilsontse88** [comment]
I mean .. can it start to the fade effect when loaded the page? (no need click any button and icon)

**Comment by snake-345** [comment]
[Example](http://jsbin.com/gecefekive/edit?css,js,output)
Is this what you want?

**Comment by wilsontse88** [comment]
Sorry. this is not.

i just want to the fade effect is autostart when the page is loaded.

**Comment by Craigy-** [comment]
+1 for fade animation with jcarouselAutoscroll plugin

**Comment by jessegilbride** [comment]
@wilsontse88 && @Craigy- 
There's a 3rd party plugin mentioned on the jcarousel main page, called [jcarouselFade](https://github.com/snake-345/jcarouselFade).

If that doesn't work for you, I'm sure there's somewhere in the jcarousel source to make a change to the transition type. I haven't dived in, but I could if it's a heavily desired thing.

**Comment by snake-345** [comment]
Sorry for long waiting. I completely forgot about this opened issue. But now I think I have good news for you @wilsontse88 @Craigy-  =)
[Another example](https://jsbin.com/qunarapuvo/edit?html,css,js,output) where jcarouselFade working with jcarouselAutoscroll properly. Maybe problem was with old version of jcarouselAutoscroll which didn't support method option? It was added in this [pull request](https://github.com/jsor/jcarousel/pull/835)
