### ISSUE TITLE
Loop / reload

### ISSUE THREAD

**Issue by gustavohellwig** [jsor/jcarousel#812]
How to make it reload/loop in the end of the show?
check this in the end: www.itaivan.com. It loads all what I have, but in the end it shops and do not loop.

thank you.

**Comment by jsor** [comment]
I can't see any usage of jCarousel. Can give me a hint where exactly you use jCarousel?

**Comment by gustavohellwig** [comment]
Hi. Tks for your return. You can see in the end of the webpage, in Parceiros (Partners). Now I decrease the speed to allow you to see. I think that it should be something simple to, when it reach the end, it start again the carousel.

**Comment by jsor** [comment]
You can use the `wrap`option set to `circular`.

```js
$('.jcarousel').jcarousel({
    wrap: 'circular'
});
```

**Comment by gustavohellwig** [comment]
u d man !!!! tks a lot !!!
