### ISSUE TITLE
Compatibility with jquery 3.1.1

### ISSUE THREAD

**Issue by jonnydevv** [jsor/jcarousel#814]
Jcarousel isn't compatible with jquery 3.1.1

**Comment by jsor** [comment]
Could you please provide a little bit more context and a reproducible test-case (eg. on jsfiddle)? What plugins are you using and what errors do you see?

**Comment by jonnydevv** [comment]
Found the problem. I was using [this](http://gsgd.co.uk/sandbox/jquery/easing/) plugin to add more easing options. Any idea of another plugin that is compatible with jquery 3.1.1?
