### ISSUE TITLE
Reload called on scroll in iOS Safari

### ISSUE THREAD

**Issue by jamiesarakinis** [jsor/jcarousel#818]
In the plugin initialization, reload is called on window resize events. In iOS Safari, resize events are called on page scroll, which is causing the carousel to behave undesirably in some circumstances. I've handled this by removing the $(window).on('resize.jcarousel', this.onWindowResize) call from the create function, but it may be useful to include an option to disable this behavior

**Comment by jsor** [comment]
Thanks for the report. I've pushed a fix in 3f180bc7982833350f572caecbb07efc94f78f6f which checks if the window dimension actually changed. Could you test the patch and report back if that fixes the issue? Thanks!

**Comment by jamiesarakinis** [comment]
Thanks, that has fixed the issue

**Comment by jsor** [comment]
Thanks for the confirmation. Fix released in [0.3.5](https://github.com/jsor/jcarousel/releases/tag/0.3.5).
