### ISSUE TITLE
The Pagination Sequence starts from 2 rather than 1

### ISSUE THREAD

**Issue by Titusdaniel** [jsor/jcarousel#820]
Hi,

The Pagination Sequence of the Basic Carousel which is Implemented starts from sequence 2 rather than 1, need your help in resolving this.
Below is the Fiddle link where it is executed.
https://jsfiddle.net/p4cLk90t/18/

**Comment by jsor** [comment]
This looks like a bug. As an immediate fix, you can set the `perPage` option to 1 for the pagination plugin.

```js
$('.jcarousel-pagination')
    // ...
    .jcarouselPagination({
        perPage: 1
    });
````

**Comment by Titusdaniel** [comment]
Hi Jan,

Thankyou for looking into the Issue, yes it has worked well.

**Comment by jsor** [comment]
Closing for now. Will look into it. Feel free to reopen if needed.
