### ISSUE TITLE
The "inactive" of jcarouselControl

### ISSUE THREAD

**Issue by chxuzzu** [jsor/jcarousel#828]
Hello,

Can I add the "inactive" of jcarouselControl to a responsive carousel?

https://sorgalla.com/jcarousel/examples/basic/
https://sorgalla.com/jcarousel/examples/responsive/

This is my example. http://www.yusunny.com/jcarousel.html

Thanks

**Comment by jsor** [comment]
Yes, just make you correctly unset `wrap` with `null` instead of `'null'`:

```js
                .jcarousel({
                    wrap: null
                })
```
Note the missing single quote around `null`.

**Comment by chxuzzu** [comment]
Thank you very much..
