### ISSUE TITLE
Auto-Scroll when mouse scroll down.

### ISSUE THREAD

**Issue by olegkhorev** [jsor/jcarousel#829]
Hello,

Just issue - when I scroll page down and once mouse became on carousel - carousel starts scrolling. We need the way to scroll page without scrolling carousel.

Do you have any solutions?

Thank you and regards,
Oleg

**Comment by jsor** [comment]
Not sure what you mean, jCarousel doesn't have automatic scrolling built in. Could you setup a reproducible test case?

**Comment by olegkhorev** [comment]
It is not auto-scroll feature. 

All I mean let's say carousel is horizontal - we scroll mouse wheel the page down. Now cursor is on position of carousel. And next instead of scrolling page down - carousel became scrolling right and page stops scrolling.

**Comment by jsor** [comment]
Still not sure what you mean, could you setup a reproducible test case?

**Comment by olegkhorev** [comment]
Please, follow here
https://dev.acopia.co.uk/home.php?shopkey=qwe123RTY

Scroll with mouse wheel to the bottom and be sure cursor is on position of carousel. Carousel items starts scrolling, and page stops scrolling.

**Comment by jsor** [comment]
That particular carousel isn't made with jCarousel 😉

**Comment by olegkhorev** [comment]
Oh sorry.
