### ISSUE TITLE
Jquery dependency is missleaded with yarn resolve.

### ISSUE THREAD

**Issue by Krleza** [jsor/jcarousel#836]
Hi,

Migrating my app to symfony webpack, I realised that jQuery version notation dependency in packages.json is miss leaded by yarn install/upgrade, seem that 2 point version numbers don't  work properly when Yarn generates the .lock file. 

The simplest solution is to change 1.7 by 1.7.0 and then everything works properly. we actually are solving this by editing the lock file, but if seem a good Idea to you, it could be changed in jcarousel next version.

Thanks for your work.

**Comment by jsor** [comment]
Thanks for the report. I've release 0.3.9 which includes the corrected jQuery version.
