### ISSUE TITLE
Rogue mistyped URL in documentation

### ISSUE THREAD

**Issue by MANICX100** [jsor/jcarousel#843]
[Config](https://sorgalla.com/jcarousel/docs/reference/configuration.html)
The above page has a link to jQuery docs animate page but it is incorrect and has an additional >
[http://api.jquery.com/animate%3E](http://api.jquery.com/animate%3E)

**Comment by MANICX100** [comment]
Two other examples
[https://developer.mozilla.org/en-US/docs/CSS/transition-timing-function%3E](https://developer.mozilla.org/en-US/docs/CSS/transition-timing-function%3E) - Dead link

[https://modernizr.com%3E/](https://modernizr.com%3E/) - another >

Finally
[https://api.jquery.com/animate/#animate-properties-options%3E](https://api.jquery.com/animate/#animate-properties-options%3E) - Works but also has an additional > symbol

**Comment by jsor** [comment]
Thanks, fixed 👍
